### ISSUE TITLE
Hangs on running

### ISSUE THREAD

**Issue by MrRazamataz** [willf668/bezos-presence#1]
Hello, I'm sure this isn't the kind of crap you want to hear buuuuuuuut, I have used Bezos presence successfully before, but now it seems to not start properly and just hangs on this screen (I'm not quite sure whats changed):
![image](https://user-images.githubusercontent.com/56600481/164978179-c8365e87-69d7-4b30-8e46-efc51d4f62f7.png)

My settings are: 
```json
{"bezos_mode": false, "remove_explicit": true, "remove_clean": true, "remove_feat": true, "check_interval": 5, "no_parentheses": true, "validApps": ["*"], "listening_to": "", "artist_first": false, "photo_override": "amazon", "apps": {"amazon": ["amazon", "Amazon Music", ["Amazon Music.exe"]]}}
```

I'm using Amazon Music from the Windows store, could that be the issue?

**Comment by MrRazamataz** [comment]
I think restarting Windows can fix this.

**Comment by wakeupinagear** [comment]
Yeah, it seems to sometimes just kinda die after leaving the PC on for more than a few days ¯\_(ツ)_/¯. Still more stable than Amazon Music. I've had better luck compiling it to an EXE with PyInstaller, fwiw.
